### ISSUE TITLE
University of Liverpool Preset

### ISSUE THREAD

**Issue by matthew-law** [cloverleaf/web#123]
**App/Service name**: University of Liverpool online application

**Link to App/Service**: https://app.askadmissions.co.uk/AYApplicantLogin/fl_ApplicantLogin.asp?id=liv

**Password requirements (If known)**: Passwords must be between 8-30 characters, contain at least 1 uppercase letter (A-Z), 1 lowercase letter (a-z), 1 number (0-9), and 1 of the following special characters: !@#$%^&*()_+|~-=\`{}[]:";'<>?,./ Spaces are not allowed.

**Comment by ChildishGiant** [comment]
I think this may be a tad niche
