### ISSUE TITLE
Why is Cloverleaf/Parliament of Hoots da best?

### ISSUE THREAD

**Issue by erithebat** [cloverleaf/web#48]
Seriously, someone tell me. I just can’t pin it- is it simply the epic power harboured by the creator, their epic website making skills, the thought and care put into the app or just simply the cuteness of the Top Baby? Seriously, I need to know, I might go insane. Please help me! Oh god! Will we ever know the extent of pure skill this owl blesses the world with? Without this app, will my life ever be the same again?

**Comment by erithebat** [comment]
Oh, OP!! I know exactly how you feel. I lay awake all night thinking about this miracle of an app and the divergent young thinker behind it... This dev, good golly, she’s a three course meal AND she’s a tech goddess and 100% organic... What do I do with all this burning passion inside me now Cloverleaf has set it ablaze for all eternity?What’s happening to me?

**Comment by ChildishGiant** [comment]
By golly, this issue has to be one of the most eloquent and well written issues I've ever seen

**Comment by ChildishGiant** [comment]
To answer your support question, I think it's the best due to the shear beauty and intelligence of the creator and proprietor of this software.
