### ISSUE TITLE
I’m not happy with this dev.

### ISSUE THREAD

**Issue by erithebat** [cloverleaf/web#49]
THE CUSTOMER ALWAYS COMES FIRST. I CANNOT BELIEVE THE TOMFOOLERY I HAVE EXPERIENCED ON THIS DAY. I expect a full refund, and a complementary Creme Egg from the dev for my trauma.

**Comment by erithebat** [comment]
I know, right?

**Comment by erithebat** [comment]
What a booby!

**Comment by TechLevelZero** [comment]
Same, can I have a refund and a cream egg too

**Comment by ChildishGiant** [comment]
![image](https://user-images.githubusercontent.com/13716824/56440204-aad82880-62e0-11e9-9c50-b1f8f114fb42.png)
👀

**Comment by erithebat** [comment]
Creme eggs for everyone please. I will not put up with this incompetence from you any longer, Owl!

**Comment by ChildishGiant** [comment]
![image](https://user-images.githubusercontent.com/13716824/56440280-d8bd6d00-62e0-11e9-9fbe-d70c321e9730.png)
