### ISSUE TITLE
dependabot auto-merge failing

### ISSUE THREAD

**Issue by Michael-Curtis0** [cloverleaf/web#673]
**Describe the bug**
Dependa auto-merge is failing

**To Reproduce**
See pulls

**Expected behavior**
Shouldn't fail auto-merges

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
[Add any other context about the problem here.](https://github.com/ahmadnassri/action-dependabot-auto-merge/issues/60)

**Comment by ChildishGiant** [comment]
This is an issue with the tests (See https://github.com/ZJONSSON/node-unzipper/issues/246) the solution would be changing to another unzipping lib in [translation.js](https://github.com/cloverleaf/web/blob/master/config/esbuild/translation.js)

**Comment by Michael-Curtis0** [comment]
https://www.npmjs.com/package/file-zip-s

A possible replacement - will give it a go later
